import 'package:flutter/material.dart';

import 'legal_document_screen.dart';

/// Full MoodBloom privacy policy, rendered in-app and linked from
/// Settings > About > Privacy policy.
class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return const LegalDocumentScreen(
      title: 'Privacy Policy',
      effectiveDate: '1 June 2026',
      intro:
          'MoodBloom ("we", "us", the "app") is a mood-tracking app built by '
          'KMUTT Group 2 as a student project. This policy explains what '
          'personal information the app collects, why, how it is stored, and '
          'the choices you have. We collect the minimum needed to run the app '
          'and we never sell your data.',
      sections: [
        LegalSection('1. Information we collect', [
          'Account information: when you sign up we store the email address '
              'and authentication identifier provided by Firebase '
              'Authentication (including Google Sign-In if you choose it). We '
              'do not store your password - authentication is handled by '
              'Firebase.',
          'Mood entries: the moods you log, including the mood type, the '
              'intensity (1-5), any note text you write, optional attached '
              'photos, and the date and time of the entry.',
          'Derived wellbeing signals: scores and pattern-detection results '
              'computed from your entries (for example garden health and the '
              'trend indicators used to offer optional supportive prompts).',
          'Device and diagnostic data: a per-install device identifier used '
              'to reconcile offline edits, crash reports via Firebase '
              'Crashlytics, and a Firebase Cloud Messaging token if you enable '
              'notifications.',
        ]),
        LegalSection('2. How we use your information', [
          'To provide the core features: saving and showing your moods, '
              'visualising your garden and history, and computing your '
              'personal trends.',
          'To offer optional, compassionate support prompts (such as a '
              'breathing exercise or journaling prompt) when your recent '
              'entries suggest it may help. You can opt out of these at any '
              'time in Settings.',
          'To send notifications you have turned on, such as a daily check-in '
              'reminder.',
          'To keep the app reliable and secure through crash diagnostics and '
              'abuse prevention.',
        ]),
        LegalSection('3. AI processing', [
          'When you ask the app to help describe a mood from text, the text '
              'you submit is sent to Google\'s Gemini model through our secure '
              'Cloud Functions proxy. We send only the text needed for that '
              'request; we do not attach your name or email to it.',
          'Supportive crisis-tier messages are never generated by AI - they '
              'are drawn from a fixed, human-reviewed library so that the most '
              'sensitive moments are deterministic and safe.',
        ]),
        LegalSection('4. Where your data is stored', [
          'Your moods are stored in your private area of Google Cloud '
              'Firestore, readable and writable only by your authenticated '
              'account. On Android the app also keeps a local encrypted-at-'
              'rest copy on your device for offline use and syncs changes when '
              'you reconnect.',
          'Attached photos are stored in Firebase Storage under your account.',
        ]),
        LegalSection('5. Biometric and PIN lock', [
          'If you enable the Privacy Lock, your PIN is never stored in plain '
              'text and never leaves your device: only a salted, '
              'computationally-hardened hash is kept locally. Biometric '
              'matching (fingerprint or face) is performed entirely by your '
              'device operating system - the app never receives your '
              'biometric data.',
        ]),
        LegalSection('6. Sharing and disclosure', [
          'We do not sell your personal information. We do not share it with '
              'advertisers.',
          'Data is processed by our infrastructure providers (Google Firebase '
              'and Google Cloud, including the Gemini API) solely to provide '
              'the app, under their respective data-protection terms.',
          'We may disclose information if required by law or to protect the '
              'safety of users.',
        ]),
        LegalSection('7. Data retention and deletion', [
          'Your data is kept while your account exists. You can delete '
              'individual entries within the allowed editing window.',
          'You can delete your entire account from Settings. Account deletion '
              'removes your profile, moods, attachments, and associated '
              'security records from our systems.',
        ]),
        LegalSection('8. Children', [
          'MoodBloom is not directed at children under 13. If you believe a '
              'child has provided us personal information, contact us and we '
              'will delete it.',
        ]),
        LegalSection('9. Not a medical service', [
          'MoodBloom is not a medical device. It cannot diagnose conditions '
              'such as bipolar disorder, depression, or anxiety, and it is not '
              'a substitute for professional care. If you are in distress, '
              'please contact a qualified professional or a local helpline.',
        ]),
        LegalSection('10. Changes and contact', [
          'We may update this policy as the app evolves; material changes will '
              'be reflected by the effective date above.',
          'Questions about this policy can be sent to the MoodBloom team at '
              'group2.moodbloom@kmutt.ac.th.',
        ]),
      ],
    );
  }
}
