import 'package:freezed_annotation/freezed_annotation.dart';

import '../../../garden/domain/entities/plant_tier.dart';
import '../../../mood/domain/entities/mood_entry.dart';
import '../../../mood/domain/entities/mood_type.dart';

part 'weekly_garden.freezed.dart';
part 'weekly_garden.g.dart';

/// Archived snapshot of one 7-day garden, persisted at
/// `users/{userId}/weeklyGardens/{weekId}` (HB-005 Track 6.1; ADR-0010 §6).
///
/// Write-once-on-archive: history is a record, not a redo. The Firestore
/// rule denies update + delete on this collection — see firebase rules
/// (architect-owned, lands in a separate commit).
///
/// `weekId` format: `'YYYY-Www'` (ISO-8601 week ordinal, two-digit week).
/// `weekStart` is local-midnight Monday of the week; `weekEnd` is
/// local-midnight of the following Monday (`weekStart + 7d`).
/// `archivedAt` is filled by the archive use case at the moment of write.
///
/// Pure-Dart entity — only imports `freezed_annotation` and sibling
/// domain types. JSON round-trip is generated by `json_serializable`.
@freezed
abstract class WeeklyGarden with _$WeeklyGarden {
  const factory WeeklyGarden({
    required String weekId,
    required DateTime weekStart,
    required DateTime weekEnd,
    required List<MoodEntry> entries,
    required List<double> healthHistory,
    required WeeklySummary summary,
    required DateTime archivedAt,
    @Default(1) int schemaV,
  }) = _WeeklyGarden;

  factory WeeklyGarden.fromJson(Map<String, Object?> json) =>
      _$WeeklyGardenFromJson(json);
}

/// Compact stats rendered on the [WeeklySummaryScreen] and the History
/// tile. Pure-Dart entity; computed by `ComputeWeeklySummaryUseCase`.
///
/// `averageMoodScore` is the mean of `MoodScore.value` over every entry
/// in the week (range [-1, +1]). `moodCounts` is a per-emotion histogram
/// — the screen pulls the top-3 from this map. `endingPlantTier` is the
/// tier on the LAST day of `healthHistory` (defaults to `resting` when
/// the list is empty). `triggeredTierCount` is the number of days the
/// engine paused with the user (caller pulls from `patterns/{date}`).
@freezed
abstract class WeeklySummary with _$WeeklySummary {
  const factory WeeklySummary({
    required double averageMoodScore,
    required Map<MoodType, int> moodCounts,
    required PlantTier endingPlantTier,
    required int totalEntryCount,
    required int triggeredTierCount,
  }) = _WeeklySummary;

  factory WeeklySummary.fromJson(Map<String, Object?> json) =>
      _$WeeklySummaryFromJson(json);
}
