// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEeN6AbPk3k5lTvx3j1ASnNzUeRbEYNeY',
    appId: '1:433750563013:web:7575f3acaf7dbd96a538ac',
    messagingSenderId: '433750563013',
    projectId: 'csc234-user-centric-mobile-app',
    authDomain: 'csc234-user-centric-mobile-app.firebaseapp.com',
    databaseURL: 'https://csc234-user-centric-mobile-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'csc234-user-centric-mobile-app.firebasestorage.app',
    measurementId: 'G-2KH6XTFCEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTnAdALXiDfJcKTvgLl-ZcdSNxJSDB308',
    appId: '1:433750563013:android:c6aa458944c606faa538ac',
    messagingSenderId: '433750563013',
    projectId: 'csc234-user-centric-mobile-app',
    databaseURL: 'https://csc234-user-centric-mobile-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'csc234-user-centric-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgaNX-sMVA8c0qGr3B_17qpBcLtlJ7VH0',
    appId: '1:433750563013:ios:5b6b1c1bf0f3fed8a538ac',
    messagingSenderId: '433750563013',
    projectId: 'csc234-user-centric-mobile-app',
    databaseURL: 'https://csc234-user-centric-mobile-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'csc234-user-centric-mobile-app.firebasestorage.app',
    iosClientId: '433750563013-scltlfi42ns0tk3q85r1ha929mkedc5n.apps.googleusercontent.com',
    iosBundleId: 'com.cssit.usercentricapp',
  );

}